
spring.datasource.url=jdbc:postgresql://db.wifdipbktxeuttffxczf.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=quote-app@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# server.port=${PORT:8081}
server.port=${PORT:8080}